---
abstract: 'common tests to check syntax of your modules'
author:
  - 'Jerome Quelin'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version '
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CompileTests
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  File::Find::Rule: 0
  Moose: 0
  Test::More: 0
  Test::Script: 0
resources:
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-CompileTests
  repository: http://github.com/jquelin/dist-zilla-plugin-compiletests
version: 0.1.0
