---
abstract: 'common tests to check syntax of your modules'
author:
  - 'Jerome Quelin'
build_requires: {}
configure_requires: {}
generated_by: 'Dist::Zilla version 1.100660'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CompileTests
provides:
  Dist::Zilla::Plugin::CompileTests:
    file: lib/Dist/Zilla/Plugin/CompileTests.pm
    version: 1.100740
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Dist::Zilla::Role::FileMunger: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Moose: 0
  Test::More: 0
  perl: 5.008
resources:
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-CompileTests
  repository: http://github.com/jquelin/dist-zilla-plugin-compiletests
version: 1.100740
